# Generated by Django 3.1.1 on 2020-10-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='Images/None/avatar.png', upload_to='Images'),
        ),
    ]
