# Generated by Django 3.1.1 on 2020-10-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20201001_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=256)),
                ('skill_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='birth_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='job',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='exprerience',
            field=models.ManyToManyField(to='Accounts.Experience'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='skills',
            field=models.ManyToManyField(to='Accounts.Skill'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='works',
            field=models.ManyToManyField(to='Accounts.Work'),
        ),
    ]
