# Generated by Django 3.1.1 on 2020-10-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20201001_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='exprerience',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='works',
        ),
    ]
