# Generated by Django 3.1.1 on 2020-10-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20201001_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='decription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='birth_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='exprerience',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.experience'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='job',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='skills',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.skill'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='works',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.work'),
        ),
        migrations.AddField(
            model_name='work',
            name='decription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
