# Generated by Django 3.1.1 on 2020-10-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20201001_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='Images/None/avatar.png', upload_to='Images/Proifle'),
        ),
    ]
