# Generated by Django 3.1.1 on 2020-10-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201001_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='Images/header/blog_defualt.jpg', upload_to='Images/header'),
        ),
    ]
